// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThanhThoaiRestaurant.Models;

#nullable disable

namespace ThanhThoaiRestaurant.Migrations
{
    [DbContext(typeof(QuanLyNhaHangContext))]
    [Migration("20250108025552_initials")]
    partial class initials
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.BanAn", b =>
                {
                    b.Property<string>("MaBan")
                        .HasMaxLength(10)
                        .HasColumnType("char(10)")
                        .IsFixedLength();

                    b.Property<int>("SucChua")
                        .HasColumnType("int");

                    b.Property<int>("TrangThaiBa")
                        .HasColumnType("int")
                        .HasColumnName("TrangThaiBA");

                    b.HasKey("MaBan");

                    b.ToTable("BanAn", (string)null);
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.ChiTietDh", b =>
                {
                    b.Property<int>("MaChiTietDh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaChiTietDh");

                    b.Property<string>("HinhAnhCt")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("HinhAnhCt");

                    b.Property<int>("MaDonHang")
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .IsFixedLength();

                    b.Property<int>("MaMon")
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .IsFixedLength();

                    b.Property<int>("SoLuongMmdh")
                        .HasColumnType("int")
                        .HasColumnName("SoLuongMMDH");

                    b.Property<string>("TenMonAnDh")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TenMonAnDH");

                    b.HasKey("MaChiTietDh")
                        .HasName("PK_DH");

                    b.HasIndex("MaDonHang");

                    b.HasIndex("MaMon");

                    b.ToTable("ChiTietDH", (string)null);
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.ChiTietGh", b =>
                {
                    b.Property<int>("MaMon")
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .IsFixedLength();

                    b.Property<int>("MaGioHang")
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .IsFixedLength();

                    b.Property<float>("GiaBan")
                        .HasColumnType("float")
                        .HasColumnName("GiaBan");

                    b.Property<float>("GiaKhuyenMai")
                        .HasColumnType("float");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("HinhAnh");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("SoLuong");

                    b.Property<int>("SoLuongMM")
                        .HasColumnType("int")
                        .HasColumnName("SoLuongMM");

                    b.Property<string>("TenMon")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TenMon");

                    b.Property<float>("ThanhTien")
                        .HasColumnType("float")
                        .HasColumnName("ThanhTien");

                    b.HasKey("MaMon", "MaGioHang")
                        .HasName("PK_CTGH");

                    b.HasIndex("MaGioHang");

                    b.ToTable("ChiTietGH", (string)null);
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.ChiTietGm", b =>
                {
                    b.Property<int>("MaMon")
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .IsFixedLength();

                    b.Property<int>("MaPhieuGm")
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .HasColumnName("MaPhieuGM")
                        .IsFixedLength();

                    b.Property<int>("SoLuongCt1")
                        .HasColumnType("int")
                        .HasColumnName("SoLuongCT1");

                    b.HasKey("MaMon", "MaPhieuGm")
                        .HasName("PK_CTGM");

                    b.HasIndex("MaPhieuGm");

                    b.ToTable("ChiTietGM", (string)null);
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.ChiTietHd", b =>
                {
                    b.Property<int>("MaChiTietHd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaChiTietHd");

                    b.Property<string>("HinhAnhHd")
                        .HasColumnType("longtext")
                        .HasColumnName("HinhAnhHd");

                    b.Property<int>("MaHd")
                        .HasColumnType("int")
                        .HasColumnName("MaHD")
                        .IsFixedLength();

                    b.Property<int>("MaMon")
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .IsFixedLength();

                    b.Property<int>("SoLuongCt")
                        .HasColumnType("int")
                        .HasColumnName("SoLuongCT");

                    b.Property<string>("TenMon")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<double>("ThanhTien")
                        .HasColumnType("double")
                        .HasColumnName("ThanhTien");

                    b.HasKey("MaChiTietHd")
                        .HasName("PK_CTHD");

                    b.HasIndex("MaHd");

                    b.HasIndex("MaMon");

                    b.ToTable("ChiTietHD", (string)null);
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.ChiTietTinNhan", b =>
                {
                    b.Property<int>("MaTinNhan")
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .IsFixedLength();

                    b.Property<string>("TenDangNhap")
                        .HasMaxLength(10)
                        .HasColumnType("char(10)")
                        .IsFixedLength();

                    b.Property<string>("NoiDung")
                        .HasColumnType("longtext")
                        .HasColumnName("NoiDung");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime");

                    b.HasKey("MaTinNhan", "TenDangNhap")
                        .HasName("PK_ChiTietTinNhan");

                    b.ToTable("ChiTietTinNhan", (string)null);
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.CPU", b =>
                {
                    b.Property<int>("MaCPU")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .IsFixedLength();

                    b.Property<string>("TenLoaiCPU")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("MaCPU");

                    b.ToTable("CPU", (string)null);
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.DanhGia", b =>
                {
                    b.Property<int>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .HasColumnName("MaDanhGia")
                        .IsFixedLength();

                    b.Property<int>("Diem")
                        .HasColumnType("int")
                        .HasColumnName("Diem")
                        .IsFixedLength();

                    b.Property<string>("HinhAnh1")
                        .HasColumnType("char")
                        .HasColumnName("HinhAnh1")
                        .IsFixedLength();

                    b.Property<string>("HinhAnh2")
                        .HasColumnType("char")
                        .HasColumnName("HinhAnh2")
                        .IsFixedLength();

                    b.Property<string>("HinhAnh3")
                        .HasColumnType("char")
                        .HasColumnName("HinhAnh3")
                        .IsFixedLength();

                    b.Property<string>("HinhAnh4")
                        .HasColumnType("char")
                        .HasColumnName("HinhAnh4")
                        .IsFixedLength();

                    b.Property<string>("HinhAnh5")
                        .HasColumnType("char")
                        .HasColumnName("HinhAnh5")
                        .IsFixedLength();

                    b.Property<int>("MaMon")
                        .HasColumnType("int")
                        .HasColumnName("MaMon")
                        .IsFixedLength();

                    b.Property<DateTime>("NgayDG")
                        .HasColumnType("datetime");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(200)
                        .HasColumnType("char(200)")
                        .HasColumnName("NoiDung")
                        .IsFixedLength();

                    b.Property<string>("TenDangNhap")
                        .HasColumnType("char")
                        .HasColumnName("TenDangNhap")
                        .IsFixedLength();

                    b.Property<string>("Video")
                        .HasColumnType("char")
                        .HasColumnName("Video")
                        .IsFixedLength();

                    b.HasKey("MaDanhGia");

                    b.ToTable("DanhGia", (string)null);
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.DatBan", b =>
                {
                    b.Property<string>("GhiChu")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MaBan")
                        .HasMaxLength(10)
                        .HasColumnType("char(10)")
                        .IsFixedLength();

                    b.Property<int>("MaKH")
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .HasColumnName("MaKH")
                        .IsFixedLength();

                    b.Property<string>("MaLichHen")
                        .HasMaxLength(10)
                        .HasColumnType("char(10)")
                        .IsFixedLength();

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NgayHen")
                        .HasColumnType("datetime");

                    b.Property<int>("SoKhach")
                        .HasColumnType("int");

                    b.Property<string>("TenKh")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TenKH");

                    b.Property<int>("TrangThaiLh")
                        .HasColumnType("int")
                        .HasColumnName("TrangThaiLH");

                    b.HasIndex("MaBan");

                    b.HasIndex("MaKH");

                    b.ToTable("DatBan", (string)null);
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.DonHang", b =>
                {
                    b.Property<int>("MaDonHang")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .IsFixedLength();

                    b.Property<string>("DiaChiNhan")
                        .HasMaxLength(10)
                        .HasColumnType("char(10)")
                        .HasColumnName("DiaChiNhan")
                        .IsFixedLength();

                    b.Property<string>("GhiChu")
                        .HasMaxLength(10)
                        .HasColumnType("char(10)")
                        .HasColumnName("GhiChu")
                        .IsFixedLength();

                    b.Property<int>("MaHd")
                        .HasColumnType("int")
                        .HasColumnName("MaHD")
                        .IsFixedLength();

                    b.Property<int>("MaKH")
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .HasColumnName("MaKH")
                        .IsFixedLength();

                    b.Property<DateTime>("NgayDatHang")
                        .HasColumnType("datetime");

                    b.Property<string>("NguoiNhan")
                        .HasMaxLength(50)
                        .HasColumnType("char(50)")
                        .HasColumnName("NguoiNhan")
                        .IsFixedLength();

                    b.Property<decimal>("PhiVanChuyen")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("SDTNN")
                        .HasMaxLength(10)
                        .HasColumnType("char(10)")
                        .HasColumnName("SDTNN")
                        .IsFixedLength();

                    b.Property<int>("TrangThaiDh")
                        .HasColumnType("int")
                        .HasColumnName("TrangThaiDH");

                    b.HasKey("MaDonHang");

                    b.HasIndex("MaHd");

                    b.HasIndex("MaKH");

                    b.ToTable("DonHang", (string)null);
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.GioHang", b =>
                {
                    b.Property<int>("MaGioHang")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .IsFixedLength();

                    b.Property<int?>("KhachHangMaKH")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongMon")
                        .HasColumnType("int")
                        .HasColumnName("SoLuongMon");

                    b.Property<float>("TienThanhToan")
                        .HasColumnType("float")
                        .HasColumnName("TienThanhToan");

                    b.Property<float>("TongGiamGia")
                        .HasColumnType("float")
                        .HasColumnName("TongGiamGia");

                    b.Property<float>("TongTien")
                        .HasColumnType("float")
                        .HasColumnName("TongTien");

                    b.HasKey("MaGioHang");

                    b.HasIndex("KhachHangMaKH");

                    b.ToTable("GioHang", (string)null);
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaHD");

                    b.Property<string>("HinhThucTT")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("HinhThucTT");

                    b.Property<int>("MaPhieuGg")
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .HasColumnName("MaPhieuGG")
                        .IsFixedLength();

                    b.Property<DateTime>("NgayHd")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayHD");

                    b.Property<double>("TienGiam")
                        .HasColumnType("double")
                        .HasColumnName("TienGiam");

                    b.Property<double>("TienTt")
                        .HasColumnType("double")
                        .HasColumnName("TienTT");

                    b.Property<double>("TongTien")
                        .HasColumnType("double")
                        .HasColumnName("TongTien");

                    b.Property<int>("TrangThaiHD")
                        .HasColumnType("int")
                        .HasColumnName("TrangThaiHD");

                    b.HasKey("MaHd");

                    b.HasIndex("MaPhieuGg");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKH")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .HasColumnName("MaKH")
                        .IsFixedLength();

                    b.Property<string>("DiaChiKh")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("DiaChiKH");

                    b.Property<int>("DiemTichLuy")
                        .HasColumnType("int");

                    b.Property<decimal>("DoanhSo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("EmailKh")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("EmailKH");

                    b.Property<string>("GioiTinhKh")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("GioiTinhKH");

                    b.Property<DateTime>("NgaySinhKh")
                        .HasColumnType("date")
                        .HasColumnName("NgaySinhKH");

                    b.Property<DateTime>("NgayTg")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayTG");

                    b.Property<string>("Sdtkh")
                        .HasMaxLength(20)
                        .HasColumnType("char(20)")
                        .HasColumnName("SDTKH")
                        .IsFixedLength();

                    b.Property<string>("TenDangNhap")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TenKh")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TenKH");

                    b.HasKey("MaKH");

                    b.HasIndex("TenDangNhap");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.ManHinh", b =>
                {
                    b.Property<int>("MaMH")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .IsFixedLength();

                    b.Property<string>("KichThuoc")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("MaMH");

                    b.ToTable("ManHinh", (string)null);
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.MonAn", b =>
                {
                    b.Property<int>("MaMon")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .IsFixedLength();

                    b.Property<string>("DonViTinh")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("longtext");

                    b.Property<double>("GiaBan")
                        .HasColumnType("double")
                        .HasColumnName("GiaBan");

                    b.Property<double>("GiaGoc")
                        .HasColumnType("double")
                        .HasColumnName("GiaGoc");

                    b.Property<double>("GiaKhuyenMai")
                        .HasColumnType("double")
                        .HasColumnName("GiaKhuyenMai");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(20)
                        .HasColumnType("char(20)")
                        .IsFixedLength();

                    b.Property<string>("HinhAnh1")
                        .HasMaxLength(20)
                        .HasColumnType("char(20)")
                        .IsFixedLength();

                    b.Property<string>("HinhAnh2")
                        .HasMaxLength(20)
                        .HasColumnType("char(20)")
                        .IsFixedLength();

                    b.Property<string>("HinhAnh3")
                        .HasMaxLength(20)
                        .HasColumnType("char(20)")
                        .IsFixedLength();

                    b.Property<int>("MaCPU")
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .IsFixedLength();

                    b.Property<int>("MaMH")
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .IsFixedLength();

                    b.Property<int>("MaNhom")
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .IsFixedLength();

                    b.Property<int>("MaOC")
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .IsFixedLength();

                    b.Property<int>("MaRam")
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .IsFixedLength();

                    b.Property<string>("MoTaDai")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("MoTaNgan")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("NgayMoBan")
                        .HasColumnType("datetime");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongDaBan")
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .IsFixedLength();

                    b.Property<string>("TenMon")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TenNhom")
                        .HasMaxLength(20)
                        .HasColumnType("char(20)")
                        .IsFixedLength();

                    b.Property<int>("TrangThaiMA")
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .IsFixedLength();

                    b.HasKey("MaMon");

                    b.HasIndex("MaCPU");

                    b.HasIndex("MaMH");

                    b.HasIndex("MaNhom");

                    b.HasIndex("MaOC");

                    b.HasIndex("MaRam");

                    b.ToTable("MonAn", (string)null);
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.NguoiDung", b =>
                {
                    b.Property<string>("TenDangNhap")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("EmailNd")
                        .HasMaxLength(50)
                        .HasColumnType("char(50)")
                        .HasColumnName("EmailND")
                        .IsFixedLength();

                    b.Property<string>("MatKhau")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("VaiTro")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("TenDangNhap")
                        .HasName("PK_NguoiDung_1");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.NhanVien", b =>
                {
                    b.Property<string>("MaNv")
                        .HasMaxLength(10)
                        .HasColumnType("char(10)")
                        .HasColumnName("MaNV")
                        .IsFixedLength();

                    b.Property<string>("Cccdnv")
                        .HasMaxLength(20)
                        .HasColumnType("char(20)")
                        .HasColumnName("CCCDNV")
                        .IsFixedLength();

                    b.Property<string>("ChucVu")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("DiaChiNv")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("DiaChiNV");

                    b.Property<string>("EmailNv")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("EmailNV");

                    b.Property<string>("GioiTinhNv")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("GioiTinhNV");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(20)
                        .HasColumnType("char(20)")
                        .HasColumnName("HinhAnh")
                        .IsFixedLength();

                    b.Property<DateTime>("NgaySinhNv")
                        .HasColumnType("date")
                        .HasColumnName("NgaySinhNV");

                    b.Property<DateTime>("NgayVl")
                        .HasColumnType("date")
                        .HasColumnName("NgayVL");

                    b.Property<string>("Sdtnv")
                        .HasMaxLength(15)
                        .HasColumnType("char(15)")
                        .HasColumnName("SDTNV")
                        .IsFixedLength();

                    b.Property<string>("TenDangNhap")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TenNv")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TenNV");

                    b.HasKey("MaNv");

                    b.HasIndex("TenDangNhap");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.NhomMonAn", b =>
                {
                    b.Property<int>("MaNhom")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .IsFixedLength();

                    b.Property<string>("TenNhom")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("MaNhom");

                    b.ToTable("NhomMonAn", (string)null);
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.OCung", b =>
                {
                    b.Property<int>("MaOC")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .IsFixedLength();

                    b.Property<string>("DungLuong")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("MaOC");

                    b.ToTable("OCung", (string)null);
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.PhieuGiamGium", b =>
                {
                    b.Property<int>("MaPhieuGg")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .HasColumnName("MaPhieuGG")
                        .IsFixedLength();

                    b.Property<int>("Diem")
                        .HasColumnType("int");

                    b.Property<string>("LoaiMa")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("PhanTram")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongPhieu")
                        .HasColumnType("int");

                    b.Property<int>("TrangThaiPgg")
                        .HasColumnType("int")
                        .HasColumnName("TrangThaiPGG");

                    b.HasKey("MaPhieuGg");

                    b.ToTable("PhieuGiamGia");
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.PhieuGoiMon", b =>
                {
                    b.Property<int>("MaPhieuGm")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .HasColumnName("MaPhieuGM")
                        .IsFixedLength();

                    b.Property<string>("GhiChu")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MaBan")
                        .HasMaxLength(10)
                        .HasColumnType("char(10)")
                        .IsFixedLength();

                    b.Property<int>("MaHd")
                        .HasColumnType("int")
                        .HasColumnName("MaHD")
                        .IsFixedLength();

                    b.Property<DateTime>("NgayGm")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayGM");

                    b.Property<string>("TenMonAnPgm")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TenMonAnPGM");

                    b.HasKey("MaPhieuGm");

                    b.HasIndex("MaBan");

                    b.HasIndex("MaHd");

                    b.ToTable("PhieuGoiMon", (string)null);
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.RAM", b =>
                {
                    b.Property<int>("MaRam")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .IsFixedLength();

                    b.Property<string>("DungLuongRam")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("MaRam");

                    b.ToTable("RAM", (string)null);
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.ThongBao", b =>
                {
                    b.Property<int>("MaTB")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .IsFixedLength();

                    b.Property<int>("MaHD")
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .IsFixedLength();

                    b.Property<string>("NoiDung")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime")
                        .HasColumnName("ThoiGian");

                    b.Property<int>("TrangThaiTB")
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .IsFixedLength();

                    b.HasKey("MaTB");

                    b.HasIndex("MaHD");

                    b.ToTable("ThongBao", (string)null);
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.TinNhan", b =>
                {
                    b.Property<int>("MaTinNhan")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .IsFixedLength();

                    b.HasKey("MaTinNhan");

                    b.ToTable("TinNhan", (string)null);
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.ChiTietDh", b =>
                {
                    b.HasOne("ThanhThoaiRestaurant.Models.DonHang", "MaDonHangNavigation")
                        .WithMany("ChiTietDhs")
                        .HasForeignKey("MaDonHang")
                        .IsRequired()
                        .HasConstraintName("fk_DH_CTDH");

                    b.HasOne("ThanhThoaiRestaurant.Models.MonAn", "MaMonNavigation")
                        .WithMany("ChiTietDhs")
                        .HasForeignKey("MaMon")
                        .IsRequired()
                        .HasConstraintName("fk_MonAn_CTDH");

                    b.Navigation("MaDonHangNavigation");

                    b.Navigation("MaMonNavigation");
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.ChiTietGh", b =>
                {
                    b.HasOne("ThanhThoaiRestaurant.Models.GioHang", "MaGioHangNavigation")
                        .WithMany("ChiTietGhs")
                        .HasForeignKey("MaGioHang")
                        .IsRequired()
                        .HasConstraintName("fk_GH1_CTGH");

                    b.HasOne("ThanhThoaiRestaurant.Models.MonAn", "MaMonNavigation")
                        .WithMany("ChiTietGhs")
                        .HasForeignKey("MaMon")
                        .IsRequired()
                        .HasConstraintName("fk_MA_CTGH");

                    b.Navigation("MaGioHangNavigation");

                    b.Navigation("MaMonNavigation");
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.ChiTietGm", b =>
                {
                    b.HasOne("ThanhThoaiRestaurant.Models.MonAn", "MaMonNavigation")
                        .WithMany("ChiTietGms")
                        .HasForeignKey("MaMon")
                        .IsRequired()
                        .HasConstraintName("fk_MonAn_CTGM");

                    b.HasOne("ThanhThoaiRestaurant.Models.PhieuGoiMon", "MaPhieuGmNavigation")
                        .WithMany("ChiTietGms")
                        .HasForeignKey("MaPhieuGm")
                        .IsRequired()
                        .HasConstraintName("fk_PGM_CTGM");

                    b.Navigation("MaMonNavigation");

                    b.Navigation("MaPhieuGmNavigation");
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.ChiTietHd", b =>
                {
                    b.HasOne("ThanhThoaiRestaurant.Models.HoaDon", "MaHdNavigation")
                        .WithMany("ChiTietHds")
                        .HasForeignKey("MaHd")
                        .IsRequired()
                        .HasConstraintName("fk_HD_CTHD");

                    b.HasOne("ThanhThoaiRestaurant.Models.MonAn", "MaMonNavigation")
                        .WithMany("ChiTietHds")
                        .HasForeignKey("MaMon")
                        .IsRequired()
                        .HasConstraintName("fk_MonAn_CTHD");

                    b.Navigation("MaHdNavigation");

                    b.Navigation("MaMonNavigation");
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.DatBan", b =>
                {
                    b.HasOne("ThanhThoaiRestaurant.Models.BanAn", "MaBanNavigation")
                        .WithMany()
                        .HasForeignKey("MaBan")
                        .HasConstraintName("fk_DatBan_BanAn");

                    b.HasOne("ThanhThoaiRestaurant.Models.KhachHang", "MaKhNavigation")
                        .WithMany()
                        .HasForeignKey("MaKH")
                        .IsRequired()
                        .HasConstraintName("fk_DatBan_Khachhang");

                    b.Navigation("MaBanNavigation");

                    b.Navigation("MaKhNavigation");
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.DonHang", b =>
                {
                    b.HasOne("ThanhThoaiRestaurant.Models.HoaDon", "MaHdNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaHd")
                        .IsRequired()
                        .HasConstraintName("fk_DonHang_HoaDon");

                    b.HasOne("ThanhThoaiRestaurant.Models.KhachHang", "MaKhNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaKH")
                        .IsRequired()
                        .HasConstraintName("fk_DonHang_Khachhang");

                    b.Navigation("MaHdNavigation");

                    b.Navigation("MaKhNavigation");
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.GioHang", b =>
                {
                    b.HasOne("ThanhThoaiRestaurant.Models.KhachHang", null)
                        .WithMany("GioHangs")
                        .HasForeignKey("KhachHangMaKH");
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.HoaDon", b =>
                {
                    b.HasOne("ThanhThoaiRestaurant.Models.PhieuGiamGium", "MaPhieuGgNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaPhieuGg")
                        .IsRequired()
                        .HasConstraintName("fk_HoaDon_PGG");

                    b.Navigation("MaPhieuGgNavigation");
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.KhachHang", b =>
                {
                    b.HasOne("ThanhThoaiRestaurant.Models.NguoiDung", "TenDangNhapNavigation")
                        .WithMany("KhachHangs")
                        .HasForeignKey("TenDangNhap")
                        .HasConstraintName("fk_TenDN1");

                    b.Navigation("TenDangNhapNavigation");
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.MonAn", b =>
                {
                    b.HasOne("ThanhThoaiRestaurant.Models.CPU", "CPU")
                        .WithMany("MonAns")
                        .HasForeignKey("MaCPU")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThanhThoaiRestaurant.Models.ManHinh", "ManHinh")
                        .WithMany("MonAns")
                        .HasForeignKey("MaMH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThanhThoaiRestaurant.Models.NhomMonAn", "MaNhomNavigation")
                        .WithMany("MonAns")
                        .HasForeignKey("MaNhom")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_MaNhom");

                    b.HasOne("ThanhThoaiRestaurant.Models.OCung", "OCung")
                        .WithMany("MonAns")
                        .HasForeignKey("MaOC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThanhThoaiRestaurant.Models.RAM", "RAM")
                        .WithMany("MonAns")
                        .HasForeignKey("MaRam")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CPU");

                    b.Navigation("MaNhomNavigation");

                    b.Navigation("ManHinh");

                    b.Navigation("OCung");

                    b.Navigation("RAM");
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.NhanVien", b =>
                {
                    b.HasOne("ThanhThoaiRestaurant.Models.NguoiDung", "TenDangNhapNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("TenDangNhap")
                        .HasConstraintName("fk_TenDN");

                    b.Navigation("TenDangNhapNavigation");
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.PhieuGoiMon", b =>
                {
                    b.HasOne("ThanhThoaiRestaurant.Models.BanAn", "MaBanNavigation")
                        .WithMany("PhieuGoiMons")
                        .HasForeignKey("MaBan")
                        .HasConstraintName("fk_PhieuGoiMon_BanAn");

                    b.HasOne("ThanhThoaiRestaurant.Models.HoaDon", "MaHdNavigation")
                        .WithMany("PhieuGoiMons")
                        .HasForeignKey("MaHd")
                        .IsRequired()
                        .HasConstraintName("fk_PhieuGoiMon_HoaDon");

                    b.Navigation("MaBanNavigation");

                    b.Navigation("MaHdNavigation");
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.ThongBao", b =>
                {
                    b.HasOne("ThanhThoaiRestaurant.Models.HoaDon", "HoaDon")
                        .WithMany("ThongBaos")
                        .HasForeignKey("MaHD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ThongBao_HoaDon");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.BanAn", b =>
                {
                    b.Navigation("PhieuGoiMons");
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.CPU", b =>
                {
                    b.Navigation("MonAns");
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDhs");
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.GioHang", b =>
                {
                    b.Navigation("ChiTietGhs");
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.HoaDon", b =>
                {
                    b.Navigation("ChiTietHds");

                    b.Navigation("DonHangs");

                    b.Navigation("PhieuGoiMons");

                    b.Navigation("ThongBaos");
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.KhachHang", b =>
                {
                    b.Navigation("DonHangs");

                    b.Navigation("GioHangs");
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.ManHinh", b =>
                {
                    b.Navigation("MonAns");
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.MonAn", b =>
                {
                    b.Navigation("ChiTietDhs");

                    b.Navigation("ChiTietGhs");

                    b.Navigation("ChiTietGms");

                    b.Navigation("ChiTietHds");
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.NguoiDung", b =>
                {
                    b.Navigation("KhachHangs");

                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.NhomMonAn", b =>
                {
                    b.Navigation("MonAns");
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.OCung", b =>
                {
                    b.Navigation("MonAns");
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.PhieuGiamGium", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.PhieuGoiMon", b =>
                {
                    b.Navigation("ChiTietGms");
                });

            modelBuilder.Entity("ThanhThoaiRestaurant.Models.RAM", b =>
                {
                    b.Navigation("MonAns");
                });
#pragma warning restore 612, 618
        }
    }
}
